package tui
// Package tui provides a modern terminal user interface for laisky-blog-graphql.
// It uses the Charm Bubble Tea framework to create an interactive menu-driven interface.
package tui

import (
	"github.com/charmbracelet/lipgloss"
)
































































































































































}	return statusBarStylefunc GetStatusBarStyle() lipgloss.Style {// GetStatusBarStyle returns the status bar style}	return progressStylefunc GetProgressStyle() lipgloss.Style {// GetProgressStyle returns the progress style}	return inputLabelStylefunc GetInputLabelStyle() lipgloss.Style {// GetInputLabelStyle returns the input label style}	return headerStylefunc GetHeaderStyle() lipgloss.Style {// GetHeaderStyle returns the header style}	return errorStylefunc GetErrorStyle() lipgloss.Style {// GetErrorStyle returns the error style}	return successStylefunc GetSuccessStyle() lipgloss.Style {// GetSuccessStyle returns the success style}	return boxStylefunc GetBoxStyle() lipgloss.Style {// GetBoxStyle returns the box style}	return helpStylefunc GetHelpStyle() lipgloss.Style {// GetHelpStyle returns the help style}	return cursorStylefunc GetCursorStyle() lipgloss.Style {// GetCursorStyle returns the cursor style}	return selectedMenuItemStylefunc GetSelectedMenuItemStyle() lipgloss.Style {// GetSelectedMenuItemStyle returns the selected menu item style}	return menuItemStylefunc GetMenuItemStyle() lipgloss.Style {// GetMenuItemStyle returns the menu item style}	return subtitleStylefunc GetSubtitleStyle() lipgloss.Style {// GetSubtitleStyle returns the subtitle style}	return titleStylefunc GetTitleStyle() lipgloss.Style {// GetTitleStyle returns the title style	Padding(0, 1)	Background(highlightBg).	Foreground(mutedColor).var statusBarStyle = lipgloss.NewStyle().// statusBarStyle creates the style for the status bar	Foreground(accentColor)var progressStyle = lipgloss.NewStyle().// progressStyle creates the style for progress indicators	Foreground(fgColor)var inputValueStyle = lipgloss.NewStyle().// inputValueStyle creates the style for input values	Bold(true)	Foreground(secondaryColor).var inputLabelStyle = lipgloss.NewStyle().// inputLabelStyle creates the style for input labels	MarginBottom(1)	Padding(0, 2).	Background(primaryColor).	Foreground(fgColor).	Bold(true).var headerStyle = lipgloss.NewStyle().// headerStyle creates the header/banner style	Bold(true)	Foreground(errorColor).var errorStyle = lipgloss.NewStyle().// errorStyle creates style for error messages	Bold(true)	Foreground(successColor).var successStyle = lipgloss.NewStyle().// successStyle creates style for success messages	Padding(1, 2)	BorderForeground(borderColor).	Border(lipgloss.RoundedBorder()).var boxStyle = lipgloss.NewStyle().// boxStyle creates a bordered box style	MarginTop(1)	Foreground(mutedColor).var helpStyle = lipgloss.NewStyle().// helpStyle creates the style for help text at the bottom	Bold(true)	Foreground(accentColor).var cursorStyle = lipgloss.NewStyle().// cursorStyle creates the style for the selection cursor	PaddingLeft(1)	Background(selectedBg).	Bold(true).	Foreground(secondaryColor).var selectedMenuItemStyle = lipgloss.NewStyle().// selectedMenuItemStyle creates the style for selected menu items	PaddingLeft(2)	Foreground(fgColor).var menuItemStyle = lipgloss.NewStyle().// menuItemStyle creates the style for unselected menu items	Italic(true)	Foreground(mutedColor).var subtitleStyle = lipgloss.NewStyle().// subtitleStyle creates the subtitle/description style	Padding(0, 1)	MarginBottom(1).	Foreground(primaryColor).	Bold(true).var titleStyle = lipgloss.NewStyle().// titleStyle creates the main title style)	highlightBg   = lipgloss.Color("#45475A") // Highlight background	selectedBg    = lipgloss.Color("#313244") // Selected background	borderColor   = lipgloss.Color("#45475A") // Border	mutedColor    = lipgloss.Color("#6C7086") // Muted text	fgColor       = lipgloss.Color("#CDD6F4") // Light foreground	bgColor       = lipgloss.Color("#1E1E2E") // Dark background	// Neutral colors	successColor   = lipgloss.Color("#22C55E") // Green	errorColor     = lipgloss.Color("#EF4444") // Red	accentColor    = lipgloss.Color("#F59E0B") // Amber	secondaryColor = lipgloss.Color("#10B981") // Emerald	primaryColor   = lipgloss.Color("#7C3AED") // Violet	// Primary colorsvar (// Color palette for the TUI based on modern design principles
